### ISSUE TITLE
AttributeError: 'GloVe' object has no attribute 'stoi'

### ISSUE THREAD

**Issue by ghost** [bzantium/PostKS#1]
if word in vectors.stoi:
AttributeError: 'GloVe' object has no attribute 'stoi'

**Comment by FlyingCat-fa** [comment]
I meet the same question, have you solve it ?

**Comment by ghost** [comment]
> I meet the same question, have you solve it ?

No，I don‘t konw if it is caused by the version of some package.

**Comment by pokedp** [comment]
I guess that's a typo, it should be "if word in vectors:".

**Comment by ghost** [comment]
> I guess that's a typo, it should be "if word in vectors:".

It works，thank you.

**Comment by ThuJiang** [comment]
> > I guess that's a typo, it should be "if word in vectors:".
> 
> It works，thank you.
Witch pytorch version did you use?

**Comment by bzantium** [comment]
I fixed this problem. Please see https://github.com/bzantium/Posterior-Knowledge-Selection/issues/5.
