### ISSUE TITLE
pre_training  bow_loss=nan

### ISSUE THREAD

**Issue by Li-rr** [bzantium/PostKS#2]
Hi，

During pre training, bow_ Loss is Nan，why is this

Kencoder embedding is initialized with Glove
decoder embedding is initialized with Glove
start pre-training
Epoch [1/5] Step [0050/1915]: bow_loss=6.4962
Epoch [1/5] Step [0100/1915]: bow_loss=6.0095
Epoch [1/5] Step [0150/1915]: bow_loss=5.9932
Epoch [1/5] Step [0200/1915]: bow_loss=5.9497
Epoch [1/5] Step [0250/1915]: bow_loss=5.9517
Epoch [1/5] Step [0300/1915]: bow_loss=5.9306
Epoch [1/5] Step [0350/1915]: bow_loss=5.9384
Epoch [1/5] Step [0400/1915]: bow_loss=5.9253
Epoch [1/5] Step [0450/1915]: bow_loss=5.9109
Epoch [1/5] Step [0500/1915]: bow_loss=5.9177
Epoch [1/5] Step [0550/1915]: bow_loss=5.9376
Epoch [1/5] Step [0600/1915]: bow_loss=5.9521
Epoch [1/5] Step [0650/1915]: bow_loss=5.9414
Epoch [1/5] Step [0700/1915]: bow_loss=5.9155
Epoch [1/5] Step [0750/1915]: bow_loss=5.9302
Epoch [1/5] Step [0800/1915]: bow_loss=5.9206
Epoch [1/5] Step [0850/1915]: bow_loss=5.9064
Epoch [1/5] Step [0900/1915]: bow_loss=nan
Epoch [1/5] Step [0950/1915]: bow_loss=nan
Epoch [1/5] Step [1000/1915]: bow_loss=nan
Epoch [1/5] Step [1050/1915]: bow_loss=nan
Epoch [1/5] Step [1100/1915]: bow_loss=nan
Epoch [1/5] Step [1150/1915]: bow_loss=nan
Epoch [1/5] Step [1200/1915]: bow_loss=nan
Epoch [1/5] Step [1250/1915]: bow_loss=nan
Epoch [1/5] Step [1300/1915]: bow_loss=nan

**Comment by bzantium** [comment]
I fixed this problem. Please see https://github.com/bzantium/Posterior-Knowledge-Selection/issues/5.
