### ISSUE TITLE
requirements 버젼 

### ISSUE THREAD

**Issue by RogerHeederer** [bzantium/PostKS#4]
안녕하세요. 해당 논문 구현에 관심이 있어서 깃을 살펴보게 되었는데요,

requirements 리스트의 버젼을 알려주실 수 있을까요??

버젼이 맞지 않아서 그런지, 에러 스무고개 중입니다 ㅠ

**Comment by bzantium** [comment]
안녕하세요. 이번에 문제가 있는 코드들을 정리하여 업데이트하였습니다. 자세한 사항은 https://github.com/bzantium/Posterior-Knowledge-Selection/pull/6 를 참고해주시고, README에 추가적으로 환경설정 방법을 추가하였습니다.
