### ISSUE TITLE
There is a bug in test.py

### ISSUE THREAD

**Issue by chikin-lau** [bzantium/PostKS#8]
There is a bug in `test.py`. when generating the mask on line 34, the sentence length is not aligned.
Solution：change`encoder_mask = (src_X == 0).unsqueeze(1).byte()`to`encoder_mask = (src_X == 0)[:, : encoder_outputs.size(0)].unsqueeze(1).byte()`

**Comment by bzantium** [comment]
Thank you for your correction! I fixed it so will close the issue :)
